In [ ]:
import numpy as np

In [ ]:
Hu#Recap
arr = np.array([[1,2,3,],[4,5,6]])

In [ ]:
type (arr)

numpy.ndarray

In [ ]:
#Dot product - m x n ||n x p
arr1 = np.random.randint(1,2,(3,1))

In [ ]:
arr.shape
arr.shape

(2, 3)

In [ ]:
arr.size

6

In [ ]:
result = np.dot(arr,arr1)

In [ ]:
print(result )

[[ 6]
 [15]]


In [ ]:
r1 = np.random.randint(10,20,(3,3))
print(r1)

[[12 10 13]
 [10 13 11]
 [16 11 19]]


In [ ]:
r2 = np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
result2 = np.dot(r1,r2)

In [ ]:
print(result2)

[[12. 10. 13.]
 [10. 13. 11.]
 [16. 11. 19.]]


In [ ]:
#M.I.= I.M=M

In [ ]:
#A.B!

In [ ]:
#mathematicla operations
#+
t1 = np.random.randint(3,6,(3,3))
t2 = np.random.randint(3,6,(3,3))

In [ ]:
print(t1)
print(t2)

[[4 3 5]
 [3 5 3]
 [5 3 4]]
[[3 5 5]
 [3 5 5]
 [4 3 4]]


In [ ]:
t3 = t1+ t2

In [ ]:
print(t3)

[[ 7  8 10]
 [ 6 10  8]
 [ 9  6  8]]


In [ ]:
 result = np.dot(arr,arr1)

In [ ]:
print(result)

[[ 6]
 [15]]


In [ ]:
t1 = np.random.randint(3, 6, (3, 3))  # Added a comma between 6 and (3, 3)
t2 = np.random.randint(3, 6, (3, 3))

In [ ]:
print(t1)
print(t2)

[[4 3 5]
 [4 4 3]
 [5 4 4]]
[[3 5 5]
 [3 5 3]
 [4 5 3]]


In [ ]:
t3 = t1 + t2

In [ ]:
t3

array([[ 7,  8, 10],
       [ 7,  9,  6],
       [ 9,  9,  7]])

In [ ]:
result = np.dot(arr,arr1)

In [ ]:
mean = t3.mean()
max = t3.max()
median = np.median(t3)
std = np.std(t3)
var = np.var(t3)

In [ ]:
print(max)

10


In [ ]:

# Trigonometric functions
# sin(x)
# cos(x)
# Tan() - sin() / cos()
# cosec - 1 / sin()
# sec - 1 / cos()
# cot - 1 / tan()



angles = np.array([0,15,30,45,60,75,90])

# sin (array)
result = np.sin(np.radians(angles))
result1 = np.cos(np.radians(angles))
result2 = np.tan(np.radians(angles))

In [ ]:
print(result)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]


In [ ]:
print(result1)

[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]


In [ ]:
print(result2)

[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [ ]:
arr = np.array([1,2,3,4,5,6])

# Reshape the array
reshapedarr = arr.reshape(3,2)

print(reshapedarr)

flattenedarr = arr.flatten()

print(flattenedarr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [ ]:
#stacking the data
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])


arr3 =  np.vstack((arr1,arr2))
print (f"The shape of arr3 is {arr3.shape}")



arr4 = np.hstack((arr1,arr2))
print(f"The shape of arr4 is {arr4.shape}")
print(arr4)

The shape of arr3 is (2, 4)
The shape of arr4 is (8,)
[ 1  2  3  4 10 20 30 40]


In [ ]:
arr = np.array([10,20,30,40,50,60,70,80])

farr = arr[arr>40]

print(farr)

[50 60 70 80]
